name: jwst-training-workshop

channels:
  - astropy
  - conda-forge

dependencies:
  - python=3.5
  - numpy>=1.6
  - scipy>=0.15
  - matplotlib>=1.3
  - astropy>=1.2.1
  - photutils>=0.3
  - scikit-image>=0.12.3
  - pandas>=0.18.1
  - glue-vispy-viewers>=0.6
  - glueviz>=0.9.1
  - jupyter
  - notebook
  - ipython
  - asdf
  - gwcs
  - beautifulsoup4
  - requests
  - keyring
  - html5lib
  - pip:
    - astroquery
